version: '3'

services:
  mongo-express:
    image: mongo-express
    container_name: sta_efigenia_mongo_express
    ports:
      - 8091:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: d841fb41
      ME_CONFIG_BASICAUTH_PASSWORD: cd0cf380!#
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: 1cf5b351
      ME_CONFIG_MONGODB_ADMINPASSWORD: 7cc57fac!#
    links:
      - mongo
    networks:
      - sta_efigenia_network

  mongo:
    image: mongo
    container_name: sta_efigenia_mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: 1cf5b351
      MONGO_INITDB_ROOT_PASSWORD: 7cc57fac!#
    ports:
      - 8090:27017
    volumes:
      - /home/volumes/mongodb/data/db:/data/db
    networks:
      - sta_efigenia_network

networks: 
    sta_efigenia_network:
      driver: bridge
